name: Reusable

on:
  workflow_call:

jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    outputs:
      test_file: ${{ steps.changes.outputs.test_file }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Check changed files
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            test_file:
              - 'test-file.txt'

      - name: Debug outputs
        run: |
          echo "test_file: ${{ steps.changes.outputs.test_file }}"

  use-changes:
    name: Use Changes
    needs: check-changes
    runs-on: ubuntu-latest
    steps:
      - name: Debug job outputs
        run: |
          echo "test_file from job output: ${{ needs.check-changes.outputs.test_file }}"

      - name: Run if changed
        if: ${{ needs.check-changes.outputs.test_file == 'true' }}
        run: echo "test-file.txt was changed!"

      - name: Run if not changed
        if: ${{ needs.check-changes.outputs.test_file != 'true' }}
        run: echo "test-file.txt was NOT changed"
